### ISSUE TITLE
Need a Wiki

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/stephenpaul2727#1]
Use the GitHub Wiki feature to document each assignment. This should minimally include the instructions for building and testing the code.

**Comment by stephenpaul2727** [comment]
Marlon, I had included a Read Me of the project inside the Assignment1 folder before. I also did create a new wiki page for assignment1 with detailed instructions to run the project now. I am closing this issue for now. If there are any suggestions, welcome to re-open the issue.
