### ISSUE TITLE
Assignment 2 Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/stephenpaul2727#10]
I have a few suggestions/comments - 

- You need to mention the steps with which I can build and run your submission (not just links where I can test it)
- Can you please include an architecture diagram with the components and flow of control?
- Ideally, you should not link the Docker containers to RabbitMQ. Access the RabbitMQ using it's public IP from the Docker containers (microservices).

Can you please make these changes and link this issue with the commit so I can review it?

**Comment by stephenpaul2727** [comment]
Hi Sneha,

I had made the changes you suggested!

Thanks

**Comment by tilaks26** [comment]
I tried testing your application but I could not understand how to. You wiki is very confusing. Can you tell me what to do once I hit the UI's IP.

**Comment by stephenpaul2727** [comment]
Sure,

From the UI you can do the following things:
1. Test whether apigateway is accessible. To do that Click "Test API Server Connection". you can see the text below changes to "Connected to the NODE API Gateway!"
2. Get Userdata from Laravel Microservice. To do that First go to this link in a separate tab. "http://129.114.104.44:8000/PhpListener". then in UI, Click "Get user data from Java Server Database through Laravel". you will see the text below getting updated.
3. Get Userdata from Python Microservice. To do that First go to this link in a separate tab. "http://129.114.104.44:5000/PythonListener". then in UI, Click "Get user data from Java Server Database through python flask". you will see the text below getting updated.
4. Getting Current time from Laravel Microservice. To do that again go to this link in a separate tab.
"http://129.114.104.44:8000/PhpListener". then in UI, Click "Get Current Time From Laravel MicroService". you will see the text below getting updated.
5. Getting cars information from Python Microservice. To do that again go to this link in a separate tab. "http://129.114.104.44:5000/PythonListener". then in UI, Click "Get Cars as Json from Python Server." you will see the text below getting updated. 

I know this is hectic to open listener window in every time. But the reason why I'm doing this is I kept the timeout for apigateway. so if it doesn't get message back from rabbit server within 3 seconds. Its going to stop itself. This is necessary for hanging processes.

**Comment by tilaks26** [comment]
It's okay for now. But next time onwards, there should just be one URL which exposes the UI of the system. You should not expose any other port internal to the system to the outside world. It defeats the purpose of the architecture.

**Comment by tilaks26** [comment]
Stephen, I spoke to Marlon. Can you please resubmit your assignment with just one entry point?

**Comment by marpierc** [comment]
@stephenpaul2727 You'll need to resubmit your assignment with the identified corrections.

**Comment by stephenpaul2727** [comment]
Hi, Sneha, I had made the changes you suggested. I need to show you the logs in the Jenkins build for the output.

**Comment by tilaks26** [comment]
You can show it to me during office hours tomorrow (but after 3). If you can't stay back, then please attach a screenshot of the logs to this issue thread. I will update your grade.

**Comment by stephenpaul2727** [comment]
I will show you in office hours. Marcus also said he will be there till 5PM. So I will be there after 3 PM
