### ISSUE TITLE
PostgreSQL version

### ISSUE THREAD

**Issue by saurabhagrawal0412** [airavata-courses/stephenpaul2727#2]
Hi @stephenpaul2727 ,
Please mention PostgreSQL version to be used in README.
It will be even more helpful if you could give a URL to download it.

**Comment by stephenpaul2727** [comment]
Hi Saurabh,

The version of PostgreSQL being used by remote database is 9.6.4

I had pushed a commit regarding the recreation of the Postgres database in your own local system. 
please refer to READ ME for more Information.

I can also provide you access to the remote database. But there is a little process of signing up for  Heroku and sharing my collaboration request. 

If this is okay with you. Please let me know. Also, let me know if you face any problems during the recreation of my database.

**Comment by saurabhagrawal0412** [comment]
While running the command:
``pg_restore --verbose --clean --no-acl --no-owner -h localhost -U myuser -d mydb latest.dump``
it asks for mydb password.
Please mention the database password as well.

**Comment by stephenpaul2727** [comment]
The password is the db password that you set up while you create your local db in psql terminal. No need of the remote db password.

**Comment by stephenpaul2727** [comment]
This tutorial best explains Postgres startup for Mac users. If you happen to use a mac, This can help a lot. Also, I had made some changes to Read ME for database recreation. If you think this is all a hassle, you can install a third party client for Postgres. I will share the remote DB credentials with you. This is the easiest process.

**Comment by stephenpaul2727** [comment]
Link for tutorial: https://www.codementor.io/devops/tutorial/getting-started-postgresql-server-mac-osx

**Comment by stephenpaul2727** [comment]
Hope you had recreated my db. I am closing this issue for now. if you want to suggest anything. you are welcome to re-open this issue

**Comment by saurabhagrawal0412** [comment]
Hey @stephenpaul2727 ,
I tried importing the dump file in my local system as well as 2 other Linux virtual machines.
Every time I try it, it asks for the password, I enter the password I entered while set up, but it fails after throwing a fatal error.
Please suggest if we can do this through Heroku.

Thanks

**Comment by stephenpaul2727** [comment]
Okay, Sure do you use mac or windows?

**Comment by saurabhagrawal0412** [comment]
Windows.

**Comment by stephenpaul2727** [comment]
Can you download postgresql maestro or some other third party client for windows. I am familiar with mac clients but not windows.

**Comment by stephenpaul2727** [comment]
No need to download any db as services talk to remote db [RESOLVED]
