### ISSUE TITLE
Regarding Third Person Access

### ISSUE THREAD

**Issue by MethkupalliVasanth** [airavata-courses/stephenpaul2727#4]
As you have mentioned in the readme. **third party postgres client for your machine like POSTICO( only available for mac) to escape all the above mentioned process.**

Is there any other option, for windows or linux users(since I am one of them).

Thanks.

**Comment by stephenpaul2727** [comment]
Postgres Maestro is one of the PostgreSQL clients that I can think of for windows. I personally didn't use it, but it is preferred by many.
