### ISSUE TITLE
Missing API Server

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/stephenpaul2727#5]
API Server which serves as entry point for the micro services are missing. Please make sure API Server is implemented.
<img width="1334" alt="30230833-027f2ee4-94b6-11e7-8aa9-a1b55215c390" src="https://user-images.githubusercontent.com/8665601/30253480-10b4c04c-9654-11e7-9446-8563c82ac4d6.png">

**Comment by stephenpaul2727** [comment]
Hi Eldho,

I have implemented the API Server for all the micro services. I have also updated the readme. Please take a look and let me know if anything requires changes. 

Thanks
