### ISSUE TITLE
Add `requirements` file in the `PythonWorld` directory.

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/stephenpaul2727#6]
You already have a `requirements.txt` for `apiserver.py`. I guess you did not put another one with `pyserver.py` because they might share the same dependencies. But there are two justifications for a separate requirements for `pyserver.py`:
1. The `Usage` requires the setting up of `pyserver.py` before the `apiserver.py`.
2. These two are inherently different services running on different systems and may not share any code (even virtual envs)

**Comment by stephenpaul2727** [comment]
Good Point, But Are you referring to the Assignment 2 branch? If so, I think the requirements.txt file is already there in the PythonWorld directory. Correct me if i'm wrong! 

Thanks

**Comment by neeraj-lad** [comment]
Yes, it is. I missed it. My bad.
