### ISSUE TITLE
The services are exposed to the client

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/stephenpaul2727#7]
I noticed that the `apiserver.py` redirects the `client.php` calls to the micro-services.
The expected implementation is:
1. The gateway receives the client requests.
2. The gateway calls the services (using a message broker).
3. The service sends the response (using a message broker).
4. The gateway sends the response to the client.

The client-gateway communications can be implemented using REST calls. I understand you might not have implemented the message broker yet, but for the first assignment, you could have performed steps 2 & 3 using REST calls.

**Comment by stephenpaul2727** [comment]
Hi Neeraj,

As far as I recall, Prof. said in class that the message broker doesn't necessarily need to be between the gateway and the microservices. It can be between intercommunication between micro services. So, I think using rest calls inbetween gateway and micro services would be acceptable. If that's not the case, I can implement that feature. Let me know.

Thanks

**Comment by neeraj-lad** [comment]
From my understanding all the communication behind the gateway should use a broker. The current structure won't enable you to replicate your services (to distribute the workload) easily. 

Besides, currently you are redirecting the client to the service via the gateway. The client can see the location of the services which subverts the gateway. The expected messaging workflow would be the four steps which I described at the start.

**Comment by stephenpaul2727** [comment]
Okay, Great point, I'll work on it!

**Comment by stephenpaul2727** [comment]
API Gateway now uses Rabbitmq for communications

**Comment by neeraj-lad** [comment]
You are exposing private API's of the services to the client. This is not the intended behavior.

**Comment by stephenpaul2727** [comment]
Issue corrected!

**Comment by neeraj-lad** [comment]
Your Python service is running at `129.114.104.44:5000`. What I mean by exposing the private API of the Python service to the client is, I (client) know exactly what url the service is running on `(129.114.104.44:5000)` and what call I need to make `(/PythonListener)`.

Now, your gateway url is `129.114.104.44:3000`. So one way for the client to call the Python service would be like `129.114.104.44:3000/PythonListener`. The gateway thus avoids exposing the Python service calls `(129.114.104.44:5000/PythonListener)` to the client.

**Comment by stephenpaul2727** [comment]
But this approach is not dynamic. If the IP Address of the VM Changes, we have to manually update the host name inside the client. I think there would be a better approach. But I couldn't figure that out.
